# Generated by Django 2.2 on 2019-07-04 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_flatuserrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='user',
        ),
        migrations.AddField(
            model_name='flat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
