# Generated by Django 2.2 on 2019-07-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190704_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='user',
        ),
    ]
