# Generated by Django 2.2 on 2019-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_society_societyflatrelation_societyuserrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isApproved',
            field=models.BooleanField(default=0),
        ),
    ]
